title: Georgios Sakkas
description: I am currently at my senior year studying Electrical and Computer Engineering at National Technical University of Athens. My main research interests are Program Analysis and Program Synthesis.
google_analytics:
theme: jekyll-theme-dinky
